name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: NPM Install 
        run: npm i

      - name: TypeScript Check
        run: tsc --noEmit
        
      - name: ESLint
        run: npm run lint